### ISSUE TITLE
Scala Steward does not update dependencies

### ISSUE THREAD

**Issue by mvillafuertem** [mvillafuertem/scalajs-react-hooks#1]
Hi @fthomas, Why this project do not receive pull request from Steward? I have checked the project name and it looks fine. Thanks in advance.

https://github.com/scala-steward/scalajs-react-hooks

**Comment by fthomas** [comment]
There was a problem with yarn. It is fixed now.

**Comment by mvillafuertem** [comment]
Thank you for fix it! :)
